# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net
 
name: $(BuildId)
 
pool:
  vmImage: 'windows-latest'
 
 
variables:   
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildMajor: '1'
  buildMinor: '0'
  buildRevision: '0'
  increment: $[counter(1,1)]
 
steps:
- task: NuGetToolInstaller@0
 
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: VSBuild@1  
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/property:VersionAssembly="$(Major).$(Minor).$(Build.BuildNumber).$(Revision)";RunWixToolsOutofProc=true'


- task: CopyFiles@1
  inputs: 
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'AutoCAD Electrical\Installer\bin\$(buildConfiguration)\en-us\*.msi' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Setups'    

- task: CopyFiles@1
  inputs: 
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'MsOffice\Installer\bin\$(buildConfiguration)\en-us\*.msi' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Setups'

- task: CopyFiles@1
  inputs: 
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'Solidworks\Installer\bin\$(buildConfiguration)\en-us\*.msi' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Setups'
