# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net
 
name: $(BuildId)
 
pool:
  vmImage: 'VS2017-Win2016'
 
 
variables:   
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildMajor: '1'
  buildMinor: '1'
  buildRevision: '$(Revision)'
 
steps:
- task: NuGetToolInstaller@0
 
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: VSBuild@1  
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/property:Major=$(buildMajor);Minor=$(buildMinor);Build=$(Build.BuildNumber);Revision=$(buildRevision);RunWixToolsOutofProc=true'
 
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/powerLoad_v$(buildMajor).$(buildMinor).$(Build.BuildNumber).zip'
    replaceExistingArchive: true
 
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Output'
